[package]
name = "streamer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasapi = "0.1.2"
log = "*"
simplelog = "*"
windows = "*"
clap = "*"